additional fix-up for IPV6 on Android API 21+
fixes: networking/interface.c:62:8: error: redefinition of 'struct in6_ifreq'

and:
error: field 'ifru_addr' has incomplete type
  struct sockaddr ifru_addr;
error: field 'ifru_dstaddr' has incomplete type
  struct sockaddr ifru_dstaddr;
...
since sockaddr was moved from linux/socket.h to sys/socket.h in newer NDK revisions